<?php

namespace GestionBundle\Repository;

/**
 * asignarconsideracionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class asignarconsideracionRepository extends \Doctrine\ORM\EntityRepository
{
}
