<?php

namespace GestionBundle\Repository;

/**
 * asignarprocesoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class asignarprocesoreRepository extends \Doctrine\ORM\EntityRepository
{
}
