<?php

namespace GestionBundle\Repository;

/**
 * asignarprocesoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class asignarprocesoRepository extends \Doctrine\ORM\EntityRepository
{
}
