<?php

namespace GestionBundle\Repository;

/**
 * asignarprocesoversionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class asignarprocesoversionRepository extends \Doctrine\ORM\EntityRepository
{
}
