<?php

namespace GestionBundle\Repository;

/**
 * configuracionlineaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class configuracionlineaRepository extends \Doctrine\ORM\EntityRepository
{
}
