<?php

namespace GestionBundle\Repository;
use \Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * conscalidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class conscalidadRepository extends \Doctrine\ORM\EntityRepository
{
	public function getPaginateConscalidads($pageSize=5, $currentPage=1) {

		/*$em = $this->getEntityManager();

		$dql = "SELECT e FROM GestionBundle\Entity\conscalidad e WHERE e.active = 1 ORDER BY e.id DESC";

		$query = $em->createQuery($dql)
				->setFirstResult($pageSize*($currentPage-1))
				->setMaxResults($pageSize);

		$paginator = new Paginator($query, $fetchJoinCollection = true);
		return $paginator;*/

	}
}
