<?php

namespace GestionBundle\Repository;

/**
 * destrezaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class destrezaRepository extends \Doctrine\ORM\EntityRepository
{
}
