<?php

namespace GestionBundle\Repository;

/**
 * detalleconfiguracionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class detalleconfiguracionRepository extends \Doctrine\ORM\EntityRepository
{
}
