<?php

namespace GestionBundle\Repository;

/**
 * detalleamfeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class detalleamfeRepository extends \Doctrine\ORM\EntityRepository
{
}
