<?php

namespace GestionBundle\Repository;

/**
 * gamaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class gamaRepository extends \Doctrine\ORM\EntityRepository
{
}
