<?php

namespace GestionBundle\Repository;

/**
 * listadotareasdesarrolloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class listadotareasdesarrolloRepository extends \Doctrine\ORM\EntityRepository
{
}
