<?php

namespace GestionBundle\Repository;

/**
 * modelosubmodeloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class modelosubmodeloRepository extends \Doctrine\ORM\EntityRepository
{
}
