<?php

namespace GestionBundle\Repository;

/**
 * opb_destrezaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class opb_destrezaRepository extends \Doctrine\ORM\EntityRepository
{
}
