<?php

namespace GestionBundle\Repository;

/**
 * operacionbasicaobsoletaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class operacionbasicaobsoletaRepository extends \Doctrine\ORM\EntityRepository
{
}
