<?php

namespace GestionBundle\Repository;

/**
 * operacionAsignadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class operacionAsignadaRepository extends \Doctrine\ORM\EntityRepository
{
}
