<?php

namespace GestionBundle\Repository;

/**
 * operacionasignadadesarrolloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class operacionasignadadesarrolloRepository extends \Doctrine\ORM\EntityRepository
{
}
