<?php

namespace GestionBundle\Repository;
use \Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * plantaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class plantaRepository extends \Doctrine\ORM\EntityRepository
{
	/*public function getPaginatePlantas($pageSize=5, $currentPage=1) {

		$em = $this->getEntityManager();

		$dql = "SELECT e FROM GestionBundle\Entity\planta e WHERE e.active = 1 ORDER BY e.id DESC";

		$query = $em->createQuery($dql)
				->setFirstResult($pageSize*($currentPage-1))
				->setMaxResults($pageSize);

		$paginator = new Paginator($query, $fetchJoinCollection = true);
		return $paginator;

	}*/

}
