<?php

namespace GestionBundle\Repository;
use \Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * procesoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class procesoRepository extends \Doctrine\ORM\EntityRepository
{
}
