<?php

namespace GestionBundle\Repository;

/**
 * submodelo_detalleamfeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class submodelo_detalleamfeRepository extends \Doctrine\ORM\EntityRepository
{
}
