<?php

namespace GestionBundle\Repository;

/**
 * tarea_amfeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tarea_amfeRepository extends \Doctrine\ORM\EntityRepository
{
}
