<?php

namespace GestionBundle\Repository;

/**
 * tareaasignadadesarrolloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tareaasignadadesarrolloRepository extends \Doctrine\ORM\EntityRepository
{
}
