<?php

namespace GestionBundle\Repository;

/**
 * tareaAsignadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tareaAsignadaRepository extends \Doctrine\ORM\EntityRepository
{
	/*public function findByid_asignarProceso()
    {
        return $this->findBy(array(), array('position' => 'ASC'));
    }*/
}
