<?php

namespace GestionBundle\Repository;
use \Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * tareaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tareaRepository extends \Doctrine\ORM\EntityRepository
{
	public function getPaginateTareas($pageSize=5, $currentPage=1) {

		$em = $this->getEntityManager();

		$dql = 'SELECT e FROM GestionBundle\Entity\tarea e WHERE e.active = 1 ORDER BY e.id DESC';

		$query = $em->createQuery($dql)
				->setFirstResult($pageSize*($currentPage-1))
				->setMaxResults($pageSize);

		$paginator = new Paginator($query, $fetchJoinCollection = true);
		return $paginator;

	}
}
