<?php

namespace GestionBundle\Repository;

/**
 * tipo_destrezaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tipo_destrezaRepository extends \Doctrine\ORM\EntityRepository
{
}
