<?php

namespace GestionBundle\Repository;

/**
 * versionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class versionRepository extends \Doctrine\ORM\EntityRepository
{
}
