gestion:
    resource: "@GestionBundle/Controller/"
    type:     annotation
    prefix:   /
app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
app_gestion:
    resource: "@GestionBundle/Resources/config/routingGestion.yml"
    prefix: /gestion
app_consultas:
    resource: "@AppBundle/Resources/config/routingConsultas.yml"
    prefix: /